on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          cache: "pip"
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"

      - run: |
          pip install -r requirements.txt
          cpanm --installdeps --notest .
          make
